#!/usr/bin/env python3
"""Check public inventory coverage, closed integration links and generated bytes."""
import json
from pathlib import Path

from ruv_manifest import apply_adoption, catalog, load_manifests

ROOT = Path(__file__).resolve().parent.parent


def main():
    paths = [ROOT / 'manifest.ruv', *sorted((ROOT / 'data/ruv/manifests').glob('*.ruv'))]
    records = load_manifests(paths, ROOT)
    apply_adoption(records, json.loads((ROOT / 'data/ruv/adoption.json').read_text()))
    repositories = {r['manifest']['repository']['url'].lower() for r in records}
    expected = set()
    for path in ('data/projects.json', 'plugins/ruvnet/data/catalog.json'):
        for project in json.loads((ROOT / path).read_text())['projects']:
            expected.add(project['repository'].lower())
    missing = expected - repositories
    if missing:
        raise ValueError(f'Canonical project inventory is missing from nexus: {sorted(missing)}')
    ids = {r['manifest']['id'] for r in records}
    for record in records:
        targets = [r['project'] for r in record['manifest']['integrations']]
        targets += [r['target'] for r in record['manifest']['relationships']]
        if set(targets) - ids:
            raise ValueError(f'Unresolved constellation links: {set(targets) - ids}')
    index = {'schemaVersion': '0.1', 'kind': 'ruv-nexus-index', 'discoveryOnly': True, 'entries': records}
    generated = {
        'data/ruv/index.json': json.dumps(index, sort_keys=True, indent=2, ensure_ascii=False) + '\n',
        'docs/ruv-catalog.md': catalog(records),
    }
    for path, content in generated.items():
        if (ROOT / path).read_bytes() != content.encode('utf-8'):
            raise ValueError(f'Stale generated output: {path}; run the documented build command')
    print(f'PASS: {len(records)} public manifests, canonical inventory coverage, resolved links and reproducible generated bytes.')


if __name__ == '__main__':
    main()
